name: Release CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish draft release immediately?'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    name: Draft / Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: ${{ inputs.publish || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
